server:
  port: 8050
  servlet:
    context-path: /user
spring:
  application:
    name: mic-user
  profiles:    active: test

#debug: true

mybatis:
  mapperLocations: classpath:mapper/*.xml
#  config-location: classpath:mybatis-config.xml
  typeAliasesPackage: com.micuser.entity

  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#showSql
logging:
  level:
    com:
      mybatis: debug
