server:
  port: 8050
  servlet:
    context-path: /user
spring:
  application:
    name: mic-user

    
#数据库配置
  datasource:
    url: jdbc:mysql://localhost:13306/springboot?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
  mvc:
    view:
      prefix: classpath:/templates/
      suffix: .html

  thymeleaf:
    cache: false
    mode: LEGACYHTML5  redis:    host: 127.0.0.1
    port: 6379
eureka:
  client:
    service-url:
     defaultZone: http://127.0.0.1:8765/eureka
    healthcheck:
     enabled: true
  instance:
    lease-renewal-interval-in-seconds: 10  #注册更新时间 默认20秒
    lease-expiration-duration-in-seconds: 30  #注册持续时间 默认90秒
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address} :${server.port}       #springboot2.0之后 使用${spring.cloud.client.ip-address}
    hostname: loaclhost




#debug: true

mybatis:
  mapperLocations: classpath:mapper/*.xml
#  config-location: classpath:mybatis-config.xml
  typeAliasesPackage: com.micuser.entity

  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#showSql
logging:
  level:
    com:
      mybatis: debug
  