server:
  port: 8765
spring:
  application:
    name: mic-eureka

eureka:
  environment: dev  #注册中心显示的环境
  client:
    service-url:
      defaultZone:  http://127.0.0.1:8765/eureka
    healthcheck:  #健康检查为true 
      enabled: true   
    #这两个选项 配置 eureka不注册自己    
    register-with-eureka: false
    fetch-registry: false